version: '3'
services:
  testify:
    build:
      context: App
      dockerfile: Dockerfile
    ports:
      - "8597:8000"
    container_name: testify
  testify-mysql:
    build:
      context: mysql
      dockerfile: Dockerfile

