version: '3'
services:
  testify:
    build: App
    volumes:
      - ./userdata:/App/src/userdata
    ports:
      - "8597:8000"
  testify-mysql:
    build: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
