version: '3'
services:
  # Give your container proper names!
  testify-checker:
    build: .
    # The checker runs a HTTP interfaces, so we need to map port 3031 to the outside (port 8000).
    ports:
      - 2597:3031
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=testify-mongo
     - MONGO_PORT=27017
     - MONGO_USER=testify_checker
     - MONGO_PASSWORD=testify_checker

  # The python checkerlib requires a mongo db!
  testify-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: testify_checker
      MONGO_INITDB_ROOT_PASSWORD: testify_checker